#! /bin/bash
###############################################################################
# (A lot of code sourced from:
# https://www.cb-net.co.uk/linux/using-lets-encrypt-with-an-nginx-docker-container-plus-bye-bye-startssl/)
#
# For a full walkthrough, please see
# https://github.com/Gorea235/nginx-rproxy
###############################################################################

# main variables
CONFIG_PATH="."
CONFIG="${CONFIG_PATH}/.env"
RPROXY_COMPOSE="${CONFIG_PATH}/docker-compose.rproxy.yml"
RENEW_LOG="./proxy-manage-renew.log"
RENEW_ECHO_FLAIR=" ================== "

# root check
if [[ $(uname) != "Darwin" && $EUID -ne 0 ]]; then
   echo This script must be run as root
   exit 1
fi
if [[ ! -f $CONFIG ]]; then
    echo The config file at $CONFIG does not exist
    echo Please create it, or set the location in this script
    exit 1
fi

# load variables
source $CONFIG

if [[ $1 == "init-rp" ]]; then
    # init volumes
    # and set owner to the config value
    mkdir -p $NGINX_VOLUMES/conf.d
    chown $STD_USER $NGINX_VOLUMES/conf.d
    mkdir -p $NGINX_VOLUMES/www/_acme
    chown $STD_USER $NGINX_VOLUMES/www/_acme
    mkdir -p $NGINX_VOLUMES/ssl
    chown $STD_USER $NGINX_VOLUMES/ssl

    # init nginx container
    docker-compose -f $RPROXY_COMPOSE up -d
elif [[ $1 == "update-rp" ]]; then
    # stop running rproxy
    docker-compose -f $RPROXY_COMPOSE down

    # pull and restart
    docker-compose -f $RPROXY_COMPOSE pull && docker-compose -f $RPROXY_COMPOSE up -d

    # clean images
    docker image prune -f
elif [[ $1 == "init-cert" ]]; then
    # init certbot
    for d in ${DOMAINS[@]}; do
        docker run -it --rm --name letsencrypt \
            -v "$NGINX_VOLUMES/ssl:/etc/letsencrypt" \
            --volumes-from $RPROXY_NAME \
            certbot/certbot \
            certonly \
            --webroot \
            --webroot-path /var/www/_acme \
            --agree-tos \
            --renew-by-default \
            -d ${d} \
            -m $EMAIL
    done
elif [[ $1 == "renew" ]]; then
    echo $RENEW_ECHO_FLAIR Running renewal check... $RENEW_ECHO_FLAIR >> $RENEW_LOG
    echo "Timestamp: $(date -Ins) ($(date))" >> $RENEW_LOG
    docker run -t --rm --name letsencrypt \
        -v "$NGINX_VOLUMES/ssl:/etc/letsencrypt" \
        --volumes-from $RPROXY_NAME \
        certbot/certbot \
        renew &>> $RENEW_LOG
    echo $RENEW_ECHO_FLAIR Renew check complete $RENEW_ECHO_FLAIR >> $RENEW_LOG
else
    echo Proxy manage script
    echo
    echo Commands:
    echo -e "\tinit-rp\t\tInitialises the reverse-proxy container"
    echo -e "\tupdate-rp\t\Restarts and updates the reverse-proxy container"
    echo -e "\tinit-cert\tInitialises the certificates"
    echo -e "\trenew\t\tCalls the certbot 'renew' with the needed volumes"
fi
